openapi: 3.0.1
info:
  title: base-admin-server
  description: base admin server
  contact:
    name: wangyx
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://base-admin-server/base-admin-server
components:
  schemas:
    errorModel:
      properties:
        errorCode:
          type: string
          description: 错误编码
        devMessage:
          type: string
          description: 错误说明
    "400":
      description: 非法请求
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorModel"
    "500":
      description: 服务器未知错误
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorModel"
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
    base:
      properties:
        id:
          type: string
          format: int64
        inx:
          type: integer
        enable:
          type: boolean
        createdBy:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedBy:
          type: string
        updatedAt:
          type: string
          format: date-time
    auth:
      allOf:
        - $ref: "#/components/schemas/base"
        - properties:
            phone:
              type: string
              description: 电话号码
            username:
              type: string
              description: 用户名称
            password:
              type: string
              description: 密码
            isAdmin:
              type: boolean
    dict:
      allOf:
        - $ref: "#/components/schemas/base"
        - properties:
            pid:
              type: string
              description: 父级id
            name:
              type: string
              description: 字典名称
            value:
              type: string
              description: 字典值
            remark:
              type: string
              description: 备注
