openapi: 3.0.1
info:
  title: base-admin-server
  description: base admin server
  contact:
    name: wangyx
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://base-admin-server/base-admin-server
tags:
  - name: dict
    description: 系统字典
paths:
  /dict:
    get:
      tags:
        - dict
      operationId: getList
      summary: 获取系统字典列表
      responses:
        "200":
          description: 查询系统字典列表成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./common.yaml#/components/schemas/dict"
        "400":
          $ref: "./common.yaml#/components/schemas/400"
        "500":
          $ref: "./common.yaml#/components/schemas/500"
    post:
      tags:
        - dict
      operationId: createDict
      summary: 创建字典
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/dict"
      responses:
        "201":
          description: 创建字典成功
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/auth"
        "400":
          $ref: "./common.yaml#/components/schemas/400"
        "500":
          $ref: "./common.yaml#/components/schemas/500"
  /dict/{uuid}:
    get:
      tags:
        - dict
      operationId: getDict
      summary: 根据ID获取系统字典
      parameters:
        - name: uuid
          in: path
          description: 字典ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 查询系统字典成功
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/dict"
        "400":
          $ref: "./common.yaml#/components/schemas/400"
        "500":
          $ref: "./common.yaml#/components/schemas/500"
    put:
      tags:
        - dict
      operationId: updateDict
      summary: 根据ID更新系统字典
      parameters:
        - name: uuid
          in: path
          description: 字典ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/dict"
      responses:
        "200":
          description: 更新系统字典成功
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/dict"
        "400":
          $ref: "./common.yaml#/components/schemas/400"
        "500":
          $ref: "./common.yaml#/components/schemas/500"
    patch:
      tags:
        - dict
      operationId: changeDictStatus
      summary: 根据ID修改系统字典状态
      parameters:
        - name: uuid
          in: path
          description: 字典ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum:
                    - active
                    - inactive
      responses:
        "200":
          description: 修改系统字典状态成功
        "400":
          $ref: "./common.yaml#/components/schemas/400"
        "500":
          $ref: "./common.yaml#/components/schemas/500"
components:
  parameters:
    name:
      name: name
      in: query
      description: 字典名
      required: false
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
