
spring:
  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.nomxeyhmujpnmcruhvbw.supabase.co:5432/postgres
    username: postgres
    password: BTK8iEobz9pjq5wz

server:
  servlet:
    context-path: /base-admin-server

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true