spring:
  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123456

server:
  servlet:
    context-path: /base-admin-server

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
