spring:
  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/noobcat?currentSchema=admin
    username:
    password:

server:
  servlet:
    context-path: /base-admin-server

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
