spring:
  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/noobcat?currentSchema=admin
    username:
    password:

server:
  servlet:
    context-path: /base-admin-server
jwt:
  secret: UUEsG/qCHuI/7+DDOSSGnHyZp077YnXeuVSQ3fKvXmJGqiea
  expiration: 86400000 # 24 hours
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true