spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.10:5432/noobman?currentSchema=admin
    username: noobman
    password: cat1to3
    hikari:
      maximum-pool-size: 16
      minimum-idle: 8
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
server:
  servlet:
    context-path: /base-admin-server
jwt:
  secret: UUEsG/qCHuI/7+DDOSSGnHyZp077YnXeuVSQ3fKvXmJGqiea
  expiration: 86400000 # 24 hours
springdoc:
  title: "Admin API"
  group: "noobcat"
  version: "0.0.1-SNAPSHOT"
  swagger-ui:
    enabled: true
    groups-order: DESC
    operationsSorter: method
    display-request-duration: true
    defaultModelRendering: model
    defaultModelExpandDepth: 4
    defaultModelsExpandDepth: 4
