import Content from "@/components/content";
import {
  TableContainer,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Card,
  Checkbox,
  FormControl,
  FormLabel,
  Input,
  Button,
  Tabs,
  TabList,
  Tab,
} from "@chakra-ui/react";
import Paginate from "react-paginate";
import { FaPlus, FaRedo, FaSearch } from "react-icons/fa";

export default function Dict() {
  return (
    <Content
      title="系统字典"
      dreadcrumb={[{ name: "系统管理" }, { name: "字典管理" }]}
    >
      <Card className="flex-1 overflow-auto">
        <Tabs colorScheme="primary">
          <TabList>
            <Tab>子模块1</Tab>
            <Tab>子模块2</Tab>
            <Tab>子模块3</Tab>
            <Tab>子模块4</Tab>
          </TabList>
        </Tabs>
        <div className="flex flex-wrap justify-between py-2 px-2 gap-4">
          <Button colorScheme="teal" size="sm" px={1} h="32px" w="32px">
            <FaPlus />
          </Button>
          <form className="flex flex-wrap justify-end gap-4">
            <FormControl className="flex items-center" w="auto" as="div">
              <FormLabel as="label" mb={0}>
                fields
              </FormLabel>
              <Input size="sm" w={150} />
            </FormControl>
            <FormControl className="flex items-center" w="auto" as="div">
              <FormLabel as="label" mb={0}>
                fields
              </FormLabel>
              <Input size="sm" w={150} />
            </FormControl>
            <FormControl className="flex items-center" w="auto" as="div">
              <FormLabel as="label" mb={0}>
                fields
              </FormLabel>
              <Input size="sm" w={150} />
            </FormControl>
            <FormControl className="flex items-center" w="auto" as="div">
              <FormLabel as="label" mb={0}>
                fields
              </FormLabel>
              <Input size="sm" w={150} />
            </FormControl>
            <Button colorScheme="primary" size="sm" px={1} h="32px" w="32px">
              <FaSearch />
            </Button>
            <Button colorScheme="gray" size="sm" px={1} h="32px" w="32px">
              <FaRedo />
            </Button>
          </form>
        </div>
        <TableContainer style={{ overflow: "auto", flex: 1 }}>
          <Table
            size="md"
            className="overflow-auto"
            variant="striped"
            colorScheme="gray"
          >
            <Thead className="sticky top-0 z-20 bg-white border-b">
              <Tr>
                <Th w={5}>#</Th>
                <Th>col1</Th>
                <Th>col2</Th>
                <Th>col3</Th>
                <Th>col4</Th>
                <Th>col5</Th>
                <Th>col6</Th>
                <Th>col7</Th>
                <Th>col8</Th>
                <Th>col9</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
              <Tr>
                <Td>
                  <Checkbox />
                </Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
                <Td>inches</Td>
              </Tr>
            </Tbody>
          </Table>
        </TableContainer>
        <div className="py-2 px-4 flex justify-between gap-8 font-semibold">
          <div className="space-x-2 text-info">
            <span>所有记录</span>
            <span className="bg-primary text-white h-8 inline-block font-semibold rounded-full px-3 py-1">
              123&nbsp;条
            </span>
          </div>
          <div className="flex space-x-4">
            <Paginate
              className="flex gap-4 items-center"
              breakLabel="..."
              nextLabel="下一页"
              nextClassName="bg-primary text-white font-semibold rounded-full px-3 py-1"
              onPageChange={() => {}}
              pageRangeDisplayed={5}
              pageCount={10}
              activeClassName="bg-primary text-white font-semibold rounded-full px-3 py-1"
              pageClassName="text-info font-semibold"
              previousLabel="上一页"
              previousClassName="bg-primary text-white font-semibold rounded-full px-3 py-1"
              renderOnZeroPageCount={null}
            />
            <div className="space-x-2 text-info">
              <span>前往</span>
              <span className="bg-primary text-white h-8 inline-block font-semibold rounded-full text-center px-4 py-1">
                1
              </span>
              <span>页</span>
            </div>
          </div>
        </div>
      </Card>
    </Content>
  );
}
