openapi: 3.0.3
info:
  title: base-admin-server
  description: base admin server
  contact:
    name: wangyx
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://base-admin-server/base-admin-server
tags:
  - name: auth
    description: 系统用户
  - name: dict
    description: 系统字典
paths:
  # auth api
  /user:
    $ref: "./user/listAndAdd.yaml"
  /user/page:
    $ref: "./user/userPage.yaml"
  /user/info:
    $ref: "./user/info.yaml"
  /user/{uuid}:
    $ref: "./user/getAndUpdate.yaml"
  /user/sign-in:
    $ref: "./user/sign-in.yaml"
  /user/{id}/toggleEnable:
    $ref: "./user/toggleEnable.yaml"
  # dict api
  /dict:
    $ref: "./dict/listAndAdd.yaml"
  /dict/page:
    $ref: "./dict/page.yaml"
  /dict/{uuid}:
    $ref: "./dict/getAndUpdate.yaml"
  /dict/{uuid}/toggleEnable:
    $ref: "./dict/toggleEnable.yaml"
